- hosts: 127.0.0.1
  connection: local
  vars_files:
    - answerfile.yml
    - answerfile_firewall.yml
  tasks:
    - name: Create a new NS Group
      nsxt_ns_groups:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        display_name: "{{ item.display_name }}"
        members: "{{ item.members | default([]) }}"
        membership_criteria: "{{ item.membership_criteria | default([]) }}"
        resource_type: "NSGroup"
        state: "{{ item.state }}"
        validate_certs: False
      with_items:
        - "{{ nsxt_ns_groups }}"
