---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
    - answerfile_firewall.yml
  tasks:
    - name: Create ip pool
      nsxt_services:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{ item.display_name }}"
        description: "{{ item.description | default(omit) }}"
        nsservice_element: "{{ item.nsservice_element }}"
        tags: "{{ item.tags | default([]) }}"
        state: present
      with_items:
        - "{{services}}"
